name: Main CI/CD Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'newbranch'  # Default branch if not provided

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}  # This uses the branch input from the manual trigger
          fetch-depth: 0 # Ensure full history

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package # If pom.xml is in root
        # run: mvn -f backend/pom.xml clean package # Uncomment if pom.xml is inside a subfolder

      - name: Transfer JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          source: "target/*.jar" # Update path if needed
          target: "/root/deployment"

      - name: Restart Application on Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 156.67.105.82
          username: root
          password: 1a2s3d4f5g@1993
          script: |
            pkill -f "java -jar" || echo "No process found"
            nohup java -jar /root/deployment/*.jar > /root/deployment/app.log 2>&1 &
            echo "Application restarted successfully"
